In [2]:
import sklearn

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [3]:
from sklearn.datasets import load_iris

In [7]:
iris= load_iris()

In [10]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
y= iris.target

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
X= iris.data

In [14]:
import pandas as pd

In [16]:
y=pd.get_dummies(y)

In [18]:
from sklearn.model_selection import train_test_split as tts

In [19]:
Xtrain,Xtest,ytrain,ytest=tts(X,y, test_size=0.25)

In [20]:
Xtrain.shape

(112, 4)

In [21]:
Xtrain= (Xtrain-Xtrain.min())/(Xtrain.max()- Xtrain.min())

In [22]:
Xtrain

array([[0.64102564, 0.46153846, 0.17948718, 0.03846154],
       [0.73076923, 0.33333333, 0.64102564, 0.23076923],
       [0.64102564, 0.47435897, 0.17948718, 0.02564103],
       [0.78205128, 0.26923077, 0.56410256, 0.17948718],
       [0.6025641 , 0.37179487, 0.16666667, 0.        ],
       [0.75641026, 0.35897436, 0.56410256, 0.17948718],
       [0.53846154, 0.37179487, 0.12820513, 0.        ],
       [0.84615385, 0.37179487, 0.62820513, 0.20512821],
       [0.75641026, 0.42307692, 0.56410256, 0.19230769],
       [0.82051282, 0.37179487, 0.69230769, 0.21794872],
       [0.64102564, 0.43589744, 0.16666667, 0.02564103],
       [0.62820513, 0.37179487, 0.19230769, 0.01282051],
       [0.71794872, 0.34615385, 0.56410256, 0.15384615],
       [0.85897436, 0.37179487, 0.69230769, 0.25641026],
       [0.64102564, 0.30769231, 0.37179487, 0.12820513],
       [0.61538462, 0.38461538, 0.17948718, 0.        ],
       [0.85897436, 0.34615385, 0.6025641 , 0.16666667],
       [0.78205128, 0.35897436,

In [23]:
Xtest= (Xtest-Xtest.min())/(Xtest.max()-Xtest.min())

In [24]:
Xtest

array([[0.64473684, 0.25      , 0.44736842, 0.11842105],
       [0.56578947, 0.38157895, 0.15789474, 0.01315789],
       [0.78947368, 0.35526316, 0.60526316, 0.14473684],
       [0.86842105, 0.38157895, 0.67105263, 0.28947368],
       [0.72368421, 0.35526316, 0.63157895, 0.25      ],
       [0.89473684, 0.39473684, 0.69736842, 0.26315789],
       [0.59210526, 0.46052632, 0.11842105, 0.01315789],
       [0.65789474, 0.44736842, 0.17105263, 0.01315789],
       [0.60526316, 0.40789474, 0.19736842, 0.01315789],
       [0.93421053, 0.38157895, 0.75      , 0.19736842],
       [0.78947368, 0.38157895, 0.63157895, 0.22368421],
       [0.82894737, 0.35526316, 0.72368421, 0.27631579],
       [0.85526316, 0.36842105, 0.59210526, 0.15789474],
       [0.81578947, 0.34210526, 0.63157895, 0.22368421],
       [0.69736842, 0.5       , 0.21052632, 0.03947368],
       [0.77631579, 0.34210526, 0.65789474, 0.19736842],
       [0.64473684, 0.46052632, 0.17105263, 0.01315789],
       [0.59210526, 0.43421053,

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [35]:
model= Sequential()
model.add(Dense(32, activation= 'relu'))
model.add(Dropout(0.33))
model.add(Dense(16, activation= 'relu'))
model.add(Dropout(0.33))
model.add(Dense(3,activation='softmax'))
model.compile(loss= 'categorical_crossentropy', optimizer= 'adam')

In [39]:
model.fit(Xtrain,ytrain,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1146
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1202
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0667
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0718
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1093
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0933
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0780
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0651
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0921
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0523
Epoch 11/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0310
Epoch 12/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0269
Epoch 13/100
4/4 [==============================] - 0s 4ms/st

In [40]:
model.predict(Xtest)

array([[0.11056878, 0.53108895, 0.35834232],
       [0.8820814 , 0.0904738 , 0.02744484],
       [0.02536265, 0.45941862, 0.5152188 ],
       [0.00532726, 0.3206183 , 0.6740545 ],
       [0.00875609, 0.33895314, 0.65229076],
       [0.00521311, 0.3253263 , 0.6694606 ],
       [0.9090065 , 0.07145595, 0.01953758],
       [0.90184397, 0.07661291, 0.02154316],
       [0.87679166, 0.09440329, 0.02880505],
       [0.00494536, 0.33051828, 0.6645364 ],
       [0.01165294, 0.381108  , 0.6072391 ],
       [0.00345953, 0.2784151 , 0.7181254 ],
       [0.02875914, 0.48565826, 0.4855826 ],
       [0.01071275, 0.3767168 , 0.6125705 ],
       [0.89473563, 0.08181615, 0.02344815],
       [0.00976882, 0.3613823 , 0.62884885],
       [0.90289664, 0.07580052, 0.02130277],
       [0.88911164, 0.08552174, 0.02536668],
       [0.00125235, 0.23153652, 0.7672111 ],
       [0.07019382, 0.5316241 , 0.39818206],
       [0.00456889, 0.29780775, 0.6976233 ],
       [0.00617129, 0.32248753, 0.6713412 ],
       [0.

In [47]:
y_pred=model.predict(Xtest)

In [48]:
y_pred.shape

(38, 3)

In [50]:
y_pred.max(axis=1)

array([0.53108895, 0.8820814 , 0.5152188 , 0.6740545 , 0.65229076,
       0.6694606 , 0.9090065 , 0.90184397, 0.87679166, 0.6645364 ,
       0.6072391 , 0.7181254 , 0.48565826, 0.6125705 , 0.89473563,
       0.62884885, 0.90289664, 0.88911164, 0.7672111 , 0.5316241 ,
       0.6976233 , 0.6713412 , 0.91999376, 0.7213716 , 0.5080756 ,
       0.6059614 , 0.48872802, 0.92681867, 0.53466004, 0.51876503,
       0.5388539 , 0.90066236, 0.5137805 , 0.50991404, 0.8511783 ,
       0.49445856, 0.9149687 , 0.51537   ], dtype=float32)

In [53]:
for i in range(y_pred.shape[0]):
    for j in range(y_pred[i].shape[0]):
        if y_pred[i][j]== y_pred.max(axis=1)[i]:
            y_pred[i][j]= 1
            
        else: 
            y_pred[i][j]= 0

In [54]:
y_pred

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [57]:
type(ytest)

pandas.core.frame.DataFrame

In [59]:
ytest

0  1  2
60   0  1  0
38   1  0  0
73   0  1  0
145  0  0  1
121  0  0  1
139  0  0  1
22   1  0  0
0    1  0  0
29   1  0  0
129  0  0  1
127  0  0  1
132  0  0  1
58   0  1  0
123  0  0  1
5    1  0  0
83   0  1  0
4    1  0  0
6    1  0  0
122  0  0  1
67   0  1  0
148  0  0  1
134  0  0  1
15   1  0  0
136  0  0  1
99   0  1  0
106  0  0  1
94   0  1  0
14   1  0  0
82   0  1  0
54   0  1  0
84   0  1  0
28   1  0  0
91   0  1  0
88   0  1  0
41   1  0  0
87   0  1  0
32   1  0  0
74   0  1  0

In [61]:
ypred=pd.DataFrame(y_pred)

In [69]:
from sklearn.metrics import confusion_matrix, classification_report as cvs

In [64]:
ypred

0    1    2
0   0.0  1.0  0.0
1   1.0  0.0  0.0
2   0.0  0.0  1.0
3   0.0  0.0  1.0
4   0.0  0.0  1.0
5   0.0  0.0  1.0
6   1.0  0.0  0.0
7   1.0  0.0  0.0
8   1.0  0.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  1.0  0.0
13  0.0  0.0  1.0
14  1.0  0.0  0.0
15  0.0  0.0  1.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  0.0  0.0  1.0
19  0.0  1.0  0.0
20  0.0  0.0  1.0
21  0.0  0.0  1.0
22  1.0  0.0  0.0
23  0.0  0.0  1.0
24  0.0  1.0  0.0
25  0.0  0.0  1.0
26  0.0  1.0  0.0
27  1.0  0.0  0.0
28  0.0  1.0  0.0
29  0.0  0.0  1.0
30  0.0  0.0  1.0
31  1.0  0.0  0.0
32  0.0  0.0  1.0
33  0.0  1.0  0.0
34  1.0  0.0  0.0
35  0.0  0.0  1.0
36  1.0  0.0  0.0
37  0.0  1.0  0.0

In [67]:
np.array(ytest).argmax(axis=1)

<IPython.core.display.Javascript object>

array([1, 0, 1, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 1, 0, 0, 2, 1, 2, 2,
       0, 2, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [68]:
confusion_matrix(np.array(ytest).argmax(axis=1),np.array(ypred).argmax(axis=1))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[12,  0,  0],
       [ 0,  8,  6],
       [ 0,  0, 12]], dtype=int64)

In [71]:
print(cvs(np.array(ytest).argmax(axis=1),np.array(ypred).argmax(axis=1)))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.57      0.73        14
           2       0.67      1.00      0.80        12

    accuracy                           0.84        38
   macro avg       0.89      0.86      0.84        38
weighted avg       0.89      0.84      0.84        38

